# logs and their full paths to display

modem_logger:
    :name:       Modem Logger
    :path:       /var/log/secure.log
    :pidfile:    /home/karl/Shared/modem/modem_logger.rb.pid

elk_m1_monitor:
    :name:       Elk M1 Monitor
    :path:       /var/log/apache2/access_log
    :pidfile:    /home/karl/Shared/ElkPerl/elk_monitor.pl.pid

weather_logger:
    :name:       Weather Logger
    :path:       /var/log/apache2/error_log
